##############################################################################
# BEST PARTITION MICRO-F1 CLUS                                               #
# Copyright (C) 2021                                                         #
#                                                                            #
# This code is free software: you can redistribute it and/or modify it under #
# the terms of the GNU General Public License as published by the Free       #
# Software Foundation, either version 3 of the License, or (at your option)  #
# any later version. This code is distributed in the hope that it will be    #
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of     #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General   #
# Public License for more details.                                           #
#                                                                            #
# Elaine Cecilia Gatto | Prof. Dr. Ricardo Cerri | Prof. Dr. Mauri           #
# Ferrandin | Federal University of Sao Carlos                               #
# (UFSCar: https://www2.ufscar.br/) Campus Sao Carlos | Computer Department  #
# (DC: https://site.dc.ufscar.br/) | Program of Post Graduation in Computer  #
# Science (PPG-CC: http://ppgcc.dc.ufscar.br/) | Bioinformatics and Machine  #
# Learning Group (BIOMAL: http://www.biomal.ufscar.br/)                      #
#                                                                            #
##############################################################################


###########################################################################
#
###########################################################################
FolderRoot = "~/Best-Partition-MiF1-Clus"
FolderScripts = "~/Best-Partition-MiF1-Clus/R"


##########################################################################
# FUNCTION R1 PARTITIONS                                               
#   Objective                                                          
#
#   Parameters                                                        
#       ds: specific dataset information                              
#       dataset_name: dataset name. It is used to save files.         
#       number_folds: number of folds created                         
#       DsFolders:path of 10-folds cross validation                   
#       FolderHClust: path of files generated by HClust and Cutree    
#       FolderR1: path of R1 partition results                        
#   Return                                                            
#       files .arff                                                   
######################################################################
validatePartitions <- function(ds,
                               id_part,
                               namesLabels,
                               dataset_name,
                               number_dataset, 
                               number_cores, 
                               number_folds, 
                               folderResults){  
  
  FolderRoot = "~/Best-Partition-MiF1-Clus"
  FolderScripts = "~/Best-Partition-MiF1-Clus/R"
  setwd(FolderScripts)
  source("utils.R")
  diretorios = directories(dataset_name, folderResults)
  
  #cat("\nGet the Folder Partition")
  FolderPartition = paste(diretorios$folderResultsDataset,
                          "/Partition-", id_part, sep="")
  
  #cat("\nData frame")
  gr = c(0)
  TodasParticoes = data.frame(gr)
  
  #cat("\nFold 1 to number_folds")
  
  if(interactive()==TRUE){ flush.console() }
  
  f = 1
  randomParalel <- foreach(f = 1:number_folds) %dopar%{  
  #while(f<=number_folds){
    
    cat("\n\n========================================")
    cat("\nFOLD: ", f)
    cat("\n========================================\n\n")
    
    FolderRoot = "~/Best-Partition-MiF1-Clus"
    FolderScripts = "~/Best-Partition-MiF1-Clus/R"
    setwd(FolderScripts)
    source("utils.R")
    diretorios = directories(dataset_name, folderResults)
    
    setwd(FolderScripts)
    source("libraries.R")
    
    ##################################################################
    converteArff <- function(arg1, arg2, arg3){
      str = paste("java -jar ", diretorios$folderUtils,
                  "/R_csv_2_arff.jar ", arg1, " ", arg2, " ", arg3, sep="")
      print(system(str))
      cat("\n")
    }
    
    ##################################################################
    #cat("\n\nFolder Split")
    FolderSplit = paste(FolderPartition, "/Split-", f, sep="")
    if(dir.exists(FolderSplit)==FALSE){
      dir.create(FolderSplit)
    }
    
    ##############################################################
    #cat("\n\nGet Partitions")
    Folder = paste(diretorios$folderPartitions, "/", dataset_name, sep="")
    FolderS = paste(Folder, "/Split-", f, sep="")
    FolderP = paste(FolderS, "/Partition-", id_part, sep="")
    
    #############################################################
    #cat("\n\nGet groups per partitions")
    setwd(FolderS)
    configP = data.frame(read.csv(paste("fold-", 
                                        f, "-groups-per-partition.csv", 
                                        sep="")))
    print(configP)
    cat("\n\n")
    #configP2 = configP[,-1]
    t = id_part - 1
    cat("\n\nT ", t)
    
    configP3 = configP[t,]
    print(configP3)
    cat("\n\n")
    
    totalGroupsPart = as.numeric(configP3$num.groups)
    cat("\n\nTotal grupos ", totalGroupsPart)
    
    ##############################################################
    nomeTr = paste(dataset_name, "-Split-Tr-", f, ".csv", sep="")
    nomeVl = paste(dataset_name, "-Split-Vl-", f, ".csv", sep="")   
    
    
    g = 1
    while(g<=totalGroupsPart){
      
      
      ###############################################################
      nome_grupo = paste("grupo_", g, sep="")           
      nome_grupo_2 = paste("Group-", g, sep="")
      
      cat("\n\n=================")
      cat("\nGroup: ", nome_grupo)
      cat("\n===============\n\n")
      
      
      #################################################################
      #cat("\n\nCreating folder group")
      FolderGroup = paste(FolderSplit, "/", nome_grupo_2, sep="")
      if(dir.exists(FolderGroup)==FALSE){dir.create(FolderGroup) }
      
      
      ################################################################
      #cat("\n\nGet the labels of this group")
      setwd(FolderP)
      part = data.frame(read.csv(paste("partition-", id_part, ".csv", sep="")))
      a = part %>% filter(., part$group == g)
      cat("\n\nTotal of labels for this group: ", nrow(a), "\n")
      
      ###############################################################
      #cat("\n\nMount group")
      nome_grupo = paste("grupo_", g, sep="")           
      grSpecThisPart = a
      totalLabelsThisGr = nrow(a)
      cat("\n\nGRUPO: ")
      print(grSpecThisPart)
      
      #################################################################
      cat("\n\nCreating Train File")
      setwd(diretorios$folderCVTR)
      nomeTr2 = paste(diretorios$folderCVTR, "/", nomeTr, sep="")
      
      ###################################################################
      cat("\nTRAIN: MOUNT GROUP\n")
      arquivoTr = data.frame(read.csv(nomeTr2), stringsAsFactors = F)
      atributosTr = arquivoTr[ds$AttStart:ds$AttEnd]
      classesTr = select(arquivoTr, grSpecThisPart$label)
      thisGroupTr = cbind(atributosTr, classesTr)
      ncols = ncol(thisGroupTr)
      
      ###############################################################
      cat("\nTRAIN: Save CSV\n")
      nomeCsTr = paste("grupo_Tr_", g, ".csv", sep="")
      nomeArTr = paste("grupo_Tr_", g, ".arff", sep="")
      setwd(FolderGroup)
      write.csv(thisGroupTr, nomeCsTr, row.names = FALSE)
      
      #####################################################################
      cat("\nTRAIN: Start End Targets\n")
      inicio = ds$LabelStart
      fim = ncol(thisGroupTr)
      ifr = data.frame(inicio, fim)
      setwd(FolderGroup)
      write.csv(ifr, "inicioFimRotulos.csv", row.names = FALSE)
      cat("\n INICIO: ", inicio, " - FIM : ", fim)
      
      #####################################################################
      cat("\nTRAIN: Convert CSV to ARFF\n")
      setwd(FolderGroup)
      arg1 = nomeCsTr
      arg2 = nomeArTr
      arg3 = paste(inicio, "-", fim, sep="")
      converteArff(arg1, arg2, arg3)
      
      ################################################################
      cat("\n\nTRAIN: Verify and correct {0} and {1}\n")
      arquivo = paste(FolderGroup, "/", nomeArTr, sep="")
      str0 = paste("sed -i 's/{0}/{0,1}/g;s/{1}/{0,1}/g' ", arquivo, sep="")
      print(system(str0))
      
      ##############################################################
      cat("\n\nCreating Validation File")
      setwd(diretorios$folderCVVL)
      nomeVl2 = paste(diretorios$folderCVVL, "/", nomeVl, sep="")
      
      ###################################################################
      cat("\n\nVALIDATION: MOUNT GROUP\n")
      arquivoVl = data.frame(read.csv(nomeVl2), stringsAsFactors = F)
      atributosVl = arquivoVl[ds$AttStart:ds$AttEnd]
      classesVl = select(arquivoVl, grSpecThisPart$label)
      thisGroupVl = cbind(atributosVl, classesVl)
      
      #################################################################
      cat("\n\nVALIDATION: Save CSV\n")
      nomeCsVl = paste("grupo_Vl_", g, ".csv", sep="")
      nomeArVl = paste("grupo_Vl_", g, ".arff", sep="")
      setwd(FolderGroup)
      write.csv(thisGroupVl, nomeCsVl, row.names = FALSE)
      
      ##################################################################
      cat("\n\nVALIDATION: Convert CSV to ARFF\n")
      setwd(FolderGroup)
      arg1 = nomeCsVl
      arg2 = nomeArVl
      arg3 = paste(inicio, "-", fim, sep="")
      converteArff(arg1, arg2, arg3)
      
      #################################################################
      cat("\n\nVALIDATION: Verify and correct {0} and {1}\n")
      arquivo = paste(FolderGroup, "/", nomeArVl, sep="")
      str0 = paste("sed -i 's/{0}/{0,1}/g;s/{1}/{0,1}/g' ", arquivo, sep="")
      system(str0)
      
      #################################################################
      
      if(totalLabelsThisGr==1){
        cat("\n\n APENAS UM RÓTULO NESTE GRUPO")
        
        setwd(FolderGroup)
        nome_config = paste("grupo_", g, ".s", sep="")
        sink(nome_config, type = "output")
        
        cat("[General]")          
        cat("\nCompatibility = MLJ08")
        
        cat("\n")
        cat("\n[Data]")
        nome_arquivo_2 = paste("grupo_Tr_", g, ".arff", sep="")
        cat(paste("\nFile = ", nome_arquivo_2, sep=""))
        nome_arquivo_3 = paste("grupo_Vl_", g, ".arff", sep="")
        cat(paste("\nTestSet = ", nome_arquivo_3, sep=""))
        
        cat("\n")
        cat("\n[Attributes]")
        cat("\nReduceMemoryNominalAttrs = yes")
        
        cat("\n")
        cat("\n[Attributes]")
        cat(paste("\nTarget = ", inicio, sep=""))
        cat("\nWeights = 1")
        
        cat("\n")
        cat("\n[Tree]")
        cat("\nHeuristic = VarianceReduction")
        cat("\nFTest = [0.001,0.005,0.01,0.05,0.1,0.125]")
        
        cat("\n")
        cat("\n[Model]")
        cat("\nMinimalWeight = 5.0")
        
        cat("\n")
        cat("\n[Output]")
        cat("\nWritePredictions = {Test}")
        cat("\n")
        sink()
        
      } else {
        
        cat("\n\n MAIS DE UM RÓTULO NESTE GRUPO")
        
        setwd(FolderGroup)
        nome_config = paste("grupo_", g, ".s", sep="")
        sink(nome_config, type = "output")
        
        cat("[General]")          
        cat("\nCompatibility = MLJ08")
        
        cat("\n")
        cat("\n[Data]")
        nome_arquivo_2 = paste("grupo_Tr_", g, ".arff", sep="")
        cat(paste("\nFile = ", nome_arquivo_2, sep=""))
        nome_arquivo_3 = paste("grupo_Vl_", g, ".arff", sep="")
        cat(paste("\nTestSet = ", nome_arquivo_3, sep=""))
        
        cat("\n")
        cat("\n[Attributes]")
        cat("\nReduceMemoryNominalAttrs = yes")
        
        cat("\n")
        cat("\n[Attributes]")
        cat(paste("\nTarget = ", inicio, "-", fim, sep=""))
        cat("\nWeights = 1")
        
        cat("\n")
        cat("\n[Tree]")
        cat("\nHeuristic = VarianceReduction")
        cat("\nFTest = [0.001,0.005,0.01,0.05,0.1,0.125]")
        
        cat("\n")
        cat("\n[Model]")
        cat("\nMinimalWeight = 5.0")
        
        cat("\n")
        cat("\n[Output]")
        cat("\nWritePredictions = {Test}")
        cat("\n")
        sink()
      }
      
      ######################################################################
      cat("\nExecute CLUS")
      nome_config2 = paste(FolderGroup, "/", nome_config, sep="")
      setwd(FolderGroup)      
      str = paste("java -jar ", diretorios$folderUtils, "/Clus.jar ", nome_config2, sep="")
      print(system(str))
      
      
      ####################################################################
      cat("\n\nOpen inicioFimRotulos.csv")
      targets = data.frame(read.csv("inicioFimRotulos.csv"))
      
      
      #################################################################
      cat("\n\nOpen predictions")
      namae2 = paste(FolderGroup, "/", nome_grupo, ".test.pred.arff", sep="")
      predicoes = data.frame(foreign::read.arff(namae2), use_xml = FALSE)
      
      ####################################################################
      cat("\nS\nPLIT PREDICTIS")
      if(targets$inicio == targets$fim){
        
        cat("\n\nOnly one label in this group")
        
        ###################################################################
        cat("\n\nSave Y_true")
        setwd(FolderGroup)
        classes = data.frame(predicoes[,1])
        names(classes) = colnames(predicoes)[1]
        write.csv(classes, "y_true.csv", row.names = FALSE)
        
        ###################################################################
        cat("\n\nSave Y_true")
        rot = paste("Pruned.p.", colnames(predicoes)[1], sep="")
        pred = data.frame(predicoes[,rot])
        names(pred) = colnames(predicoes)[1]
        setwd(FolderGroup)
        write.csv(pred, "y_predict.csv", row.names = FALSE)
        
        
        ################################################################
        rotulos = c(colnames(classes))
        n_r = length(rotulos)
        
        if(interactive()==TRUE){ flush.console() }
        gc()
        
      } else {
        
        #################################################################
        cat("\n\nMore than one label in this group")
        comeco = 1+(targets$fim - targets$inicio)
        
        
        ####################################################################
        cat("\n\nSave Y_true")
        classes = data.frame(predicoes[,1:comeco])
        setwd(FolderGroup)
        write.csv(classes, "y_true.csv", row.names = FALSE)
        
        
        ################################################################
        cat("\n\nSave Y_true")
        rotulos = c(colnames(classes))
        n_r = length(rotulos)
        nomeColuna = c()
        t = 1 
        while(t <= n_r){
          nomeColuna[t] = paste("Pruned.p.", rotulos[t], sep="")
          t = t + 1
          gc()
        }
        pred = data.frame(predicoes[nomeColuna])
        names(pred) = rotulos
        setwd(FolderGroup)
        write.csv(pred, "y_predict.csv", row.names = FALSE)
        
        if(interactive()==TRUE){ flush.console() }
        gc()
      } # FIM DO ELSE
      
      nome1 = paste("grupo_Tr_", g, ".arff", sep="")
      nome2 = paste("grupo_Vl_", g, ".arff", sep="")
      nome3 = paste("grupo_Tr_", g, ".csv", sep="")
      nome4 = paste("grupo_Vl_", g, ".csv", sep="")
      nome5 = paste("grupo_", g, ".model", sep="")
      nome6 = paste("grupo_", g, ".s", sep="")
      
      setwd(FolderGroup)
      unlink(nome1, recursive = TRUE)
      unlink(nome2, recursive = TRUE)
      unlink(nome3, recursive = TRUE)
      unlink(nome4, recursive = TRUE)
      unlink(nome5, recursive = TRUE)
      unlink(nome6, recursive = TRUE)
      
      cat("\nIncrement group: ", g)
      g = g + 1
      
      if(interactive()==TRUE){ flush.console() }
      
      gc()
    } # fim do grupo
    
    if(interactive()==TRUE){ flush.console() }
    
    
    #f = f + 1
    gc()
  }
  
  if(interactive()==TRUE){ flush.console() }
  gc()
  
  cat("\n############################################################")
  cat("\n# BUILD AND VALIDATE id_part: END                          #")
  cat("\n############################################################")
  cat("\n\n\n\n")
} 


######################################################################
# FUNCTION GATHER PREDICTS R1 PARTITIONS                              
#   Objective                           
#      From the file "test.pred.arff", separates the real labels and
#     the predicted labels to
#      generate the confusion matrix to evaluate the partition.
#   Parameters                                                 
#       ds: specific dataset information                       
#       dataset_name: dataset name. It is used to save files.  
#       number_folds: number of folds created                  
#       FolderR1: path of R1 partition results                 
#   Return                                                     
#       true labels and predicts labels                        
###############################################################
juntaResultados <- function(ds,
                            id_part,
                            namesLabels,
                            dataset_name,
                            number_dataset, 
                            number_cores, 
                            number_folds, 
                            folderResults){
  
  retorno = list()
  
  diretorios = directories(dataset_name, folderResults)
  
  FolderPartition = paste(diretorios$folderResultsDataset, "/Partition-", id_part, sep="")
  
  # start build partitions
  # do fold 1 até o último fold
  f = 1
  gatherParal <- foreach(f = 1:number_folds) %dopar%{
    
    
    
    # data frame
    apagar = c(0)
    y_true = data.frame(apagar)
    y_pred = data.frame(apagar)  
    
    cat("\n\nFold: ", f)
    
    FolderSplit = paste(FolderPartition, "/Split-", f, sep="")
    FolderS = paste(diretorios$folderPartitions, "/", dataset_name, "/Split-", f, sep="")
    
    ####################################################################################
    cat("\n\nGet groups per partitions")
    setwd(FolderS)
    configP = data.frame(read.csv(paste("fold-", f, "-groups-per-partition.csv", sep="")))
    t = id_part - 1
    configP3 = configP[t,]
    totalGroupsPart = as.numeric(configP3$num.groups)
    cat("\n\nTotal grupos ", totalGroupsPart)
    
    g = 1
    while(g<=totalGroupsPart){
      
      cat("\n\nGroup: ", g)
      
      FolderGroup = paste(FolderSplit, "/Group-", g, sep="")
      
      cat("\n\nGather y_true ", g)
      setwd(FolderGroup)
      y_true_gr = data.frame(read.csv("y_true.csv"))
      y_true = cbind(y_true, y_true_gr)
      print(nrow(y_true))
      
      cat("\n\nGather y_predict ", g)
      y_pred_gr = data.frame(read.csv("y_predict.csv"))
      y_pred = cbind(y_pred, y_pred_gr)
      print(nrow(y_pred))
      
      cat("\n\nDeleting files")
      unlink("y_true.csv", recursive = TRUE)
      unlink("y_predict.csv", recursive = TRUE)
      unlink("inicioFimRotulos.csv", recursive = TRUE)
      
      g = g + 1
      gc()
    }
    
    cat("\n\nSave files ", g, "\n")
    setwd(FolderSplit)
    y_pred = y_pred[,-1]
    y_true = y_true[,-1]
    write.csv(y_pred, "y_predict.csv", row.names = FALSE)
    write.csv(y_true, "y_true.csv", row.names = FALSE)
    
    gc()
  } # fim do foreach
  
  retorno$id_part = id_part
  retorno$ds = ds
  retorno$dataset_name = dataset_name
  retorno$number_folds = number_folds
  
  return(retorno)
  
  gc()
  cat("\n############################################################")
  cat("\n# Gather Predicts: END                                     #") 
  cat("\n############################################################")
  cat("\n\n\n\n")
  
} # fim da função


####################################################################
# FUNCTION EVALUATION R1 PARTITIONS                                 
#   Objective                                                       
#      Evaluates the R1 partitions                                  
#   Parameters                                                      
#       ds: specific dataset information                            
#       dataset_name: dataset name. It is used to save files.       
#       number_folds: number of folds created                       
#       FolderR1: path of R1 partition results                      
#   Return                                                          
#       Assessment measures for each R1 partition                   
#####################################################################
avalia <- function(ds,
                   id_part,
                   namesLabels,
                   dataset_name,
                   number_dataset, 
                   number_cores, 
                   number_folds, 
                   folderResults){
  
  retorno = list()
  
  diretorios = directories(dataset_name, folderResults)
  
  FolderPartition = paste(diretorios$folderResultsDataset,
                          "/Partition-", id_part, sep="")
  
  # from fold = 1 to number_folder
  f = 1
  evalParal <- foreach(f = 1:number_folds) %dopar%{  
    
    library("mldr")
    library("utiml")
    
    cat("\nFold: ", f)
    
    # data frame
    apagar = c(0)
    confMatPartitions = data.frame(apagar)
    partitions = c()
    
    # specifyin folder for the fold
    FolderSplit = paste(FolderPartition, "/Split-", f, sep="")
    
    # get the true and predict lables
    setwd(FolderSplit)
    y_true = data.frame(read.csv("y_true.csv"))
    y_pred = data.frame(read.csv("y_predict.csv"))
    
    # compute measures multilabel
    y_true2 = data.frame(sapply(y_true, function(x) as.numeric(as.character(x))))
    y_true3 = mldr_from_dataframe(y_true2 , 
                                  labelIndices = seq(1,ncol(y_true2 )), 
                                  name = "y_true2")
    y_pred2 = sapply(y_pred, function(x) as.numeric(as.character(x)))
    
    #cat("\n\t\tSave Confusion Matrix")
    setwd(FolderSplit)
    salva3 = paste("Conf-Mat-Fold-", f, ".txt", sep="")
    sink(file=salva3, type="output")
    confmat = multilabel_confusion_matrix(y_true3, y_pred2)
    print(confmat)
    sink()
    
    # creating a data frame
    confMatPart = multilabel_evaluate(confmat)
    confMatPart = data.frame(confMatPart)
    names(confMatPart) = paste("Fold-", f, sep="")      
    namae = paste("Split-", f,"-Evaluated.csv", sep="")
    write.csv(confMatPart, namae)  
    
    # delete files
    setwd(FolderSplit)
    unlink("y_true.csv", recursive = TRUE)
    unlink("y_predict.csv", recursive = TRUE)
    
    gc()
  } # end folds
  
  retorno$id_part = id_part
  retorno$ds = ds
  retorno$dataset_name = dataset_name
  retorno$number_folds = number_folds
  
  return(retorno)
  
  gc()
  cat("\n############################################################")
  cat("\n# Evaluation Folds: END                                    #")
  cat("\n############################################################")
  cat("\n\n\n\n")
}


#######################################################################
# FUNCTION GATHER EVALUATIONS                             
#   Objective                                             
#       Gather metrics for all folds                      
#   Parameters                                            
#       ds: specific dataset information                  
#       dataset_name: dataset name. It is used to save files.
#       number_folds: number of folds created                
#       FolderR1: path of R1 partition results               
#   Return                                                   
#       Assessment measures for all folds                    
###################################################################
juntaAvaliacoes <- function(ds,
                            id_part,
                            namesLabels,
                            dataset_name,
                            number_dataset, 
                            number_cores, 
                            number_folds, 
                            folderResults){  
  
  retorno = list()
  
  diretorios = directories(dataset_name, folderResults)
  
  FolderPartition = paste(diretorios$folderResultsDataset,
                          "/Partition-", id_part, sep="")
  
  # vector with names
  measures = c("accuracy","average-precision","clp","coverage","F1",
               "hamming-loss","macro-AUC",
               "macro-F1","macro-precision","macro-recall","margin-loss",
               "micro-AUC","micro-F1",
               "micro-precision","micro-recall","mlp","one-error",
               "precision","ranking-loss",
               "recall","subset-accuracy","wlp")
  
  # data frame
  apagar = c(0)
  avaliado4 = data.frame(apagar)
  folds = c(0)
  nomesFolds = c(0)
  
  # from fold = 1 to number_folders
  f = 1
  while(f<=number_folds){  
    
    cat("\nFold: ", f)
    
    # specifying folder for the fold
    FolderSplit = paste(FolderPartition, "/Split-", f, sep="")
    setwd(FolderSplit)
    str = paste("Split-", f, "-Evaluated.csv", sep="")
    avaliado = data.frame(read.csv(str))
    names(avaliado)[1] = "medidas"
    avaliado2 = data.frame(avaliado[order(avaliado$medidas, decreasing = FALSE),])
    avaliado3 = data.frame(avaliado2[,-1])
    avaliado4 = cbind(avaliado4, avaliado3)
    #names(avaliado4)[f+1] = paste("Fold-", f, sep="")
    nomesFolds[f] = paste("Fold-", f, sep="")
    
    setwd(FolderSplit)
    unlink(str, recursive = TRUE)
    
    f = f + 1
    gc()
    
  } # end folds
  
  #cat("\nSAVE MEASURES")
  avaliado4$apagar = measures
  colnames(avaliado4) = c("measures", nomesFolds)
  
  setwd(FolderPartition)
  nome3 = paste("Partition-", id_part, "-Evaluated-Validation.csv", sep="")
  write.csv(avaliado4, nome3, row.names = FALSE)
  
  setwd(diretorios$folderResultsDataset)
  write.csv(avaliado4, nome3, row.names = FALSE)
  
  
  nome4 = paste("Partition-", id_part, "-Mean-10-folds-Validation.csv", sep="")
  avaliado5 = avaliado4[,-1]
  avaliado6 = data.frame(apply(avaliado5, 1, mean))
  colnames(avaliado6) = "Mean-10Folds"
  avaliado7 = cbind(measures, avaliado6)
  
  setwd(FolderPartition)
  write.csv(avaliado7, nome4)
  
  setwd(diretorios$folderResultsDataset)
  write.csv(avaliado7, nome4)
  
  retorno$id_part = id_part
  retorno$ds = ds
  retorno$dataset_name = dataset_name
  retorno$number_folds = number_folds
  retorno$FolderPartition = FolderPartition
  retorno$evaluated10F = avaliado4
  retorno$evaluatedMean = avaliado7
  
  return(retorno)
  
  gc()
  cat("\n############################################################")
  cat("\n# Evaluated Partition: END                                 #")
  cat("\n############################################################")
  cat("\n\n\n\n")
}



##########################################################################
#
##########################################################################
validate <- function(ds,
                     namesLabels,
                     dataset_name,
                     number_dataset, 
                     number_cores, 
                     number_folds, 
                     folderResults){
  
  ##########################################################################
  FolderRoot = "~/Best-Partition-MiF1-Clus"
  FolderScripts = "~/Best-Partition-MiF1-Clus/R"
  setwd(FolderScripts)
  source("utils.R")
  
  diretorios = directories(dataset_name, folderResults)
  
  # from partition 2 to last partition (n)
  count = 2
  id_part = 2
  while(id_part<ds$Labels){
    
    cat("\nPARTITION: ", id_part, "\n")
    
    diretorios = directories(dataset_name, folderResults)
    
    cat("\n\nCreating folder partition")
    FolderPartition = paste(diretorios$folderResultsDataset, 
                            "/Partition-", id_part, sep="")
    if(dir.exists(FolderPartition)==FALSE){
      dir.create(FolderPartition)
    }
    
    cat("\n\n##########################################################")
    cat("\n# VALIDATE: Build and Validate Partitions                  #")
    cat("\n############################################################\n\n")
    timeBuild = system.time(resVP <- validatePartitions(ds,
                                                        id_part,
                                                        namesLabels,
                                                        dataset_name,
                                                        number_dataset, 
                                                        number_cores, 
                                                        number_folds, 
                                                        folderResults))
    
    
    cat("\n\n##########################################################")
    cat("\n# VALIDATE: Matrix Correlation                             #")
    cat("\n############################################################\n\n")
    timeSplit = system.time(resGatherVal <- juntaResultados(ds,
                                                            id_part,
                                                            namesLabels,
                                                            dataset_name,
                                                            number_dataset, 
                                                            number_cores, 
                                                            number_folds, 
                                                            folderResults)) 
    
    
    cat("\n\n##########################################################")
    cat("\n# VALIDATE:  evaluation Fold                               #")
    cat("\n############################################################\n\n")
    timeAvalia = system.time(resEVal <- avalia(ds,
                                               id_part,
                                               namesLabels,
                                               dataset_name,
                                               number_dataset, 
                                               number_cores, 
                                               number_folds, 
                                               folderResults))
    
    
    cat("\n\n##########################################################")
    cat("\n# VALIDATE:  Gather Evaluation                             #")
    cat("\n############################################################\n\n")
    timeGather = system.time(resValEval <- juntaAvaliacoes(ds,
                                                           id_part,
                                                           namesLabels,
                                                           dataset_name,
                                                           number_dataset, 
                                                           number_cores, 
                                                           number_folds, 
                                                           folderResults)) 
    
    
    cat("\n\n##########################################################")
    cat("\n# VALIDATE: Save Runtime                                   #")
    cat("\n############################################################\n\n")
    Runtime = rbind(timeBuild, timeSplit, timeAvalia, timeGather)
    setwd(FolderPartition)
    name2 = paste("Partition-", id_part ,"-Runtime-Validation.csv", sep="")
    write.csv(Runtime, name2)
    
    
    # count
    id_part = id_part + 1
    count = count + 1
    
    gc()
  }
  
  gc()
  cat("\n\n##########################################################")
  cat("\n# END VALIDATE                                             #")
  cat("\n############################################################\n\n")
}


#######################################################################
# Please, any errors, contact us: elainececiliagatto@gmail.com        #
# Thank you very much!                                                #
#######################################################################